#!/usr/bin/env bash                                                                                         
# Using while loops displaying Best Scholl 10 times                                                                                                                                                          
COUNTER=0                                                                                                                                                               
while [ $COUNTER -lt 10 ]  
